export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER = 'USER';

export const FETCH_TWITTERS_REQUEST = 'FETCH_TWITTERS_REQUEST';
export const FETCH_TWITTERS_SUCCESS = 'FETCH_TWITTERS_SUCCESS';
export const FETCH_TWITTERS_FAILURE = 'FETCH_TWITTERS_FAILURE';

export const FETCH_TWITTER_SAVE_REQUEST = 'FETCH_TWITTER_SAVE_REQUEST';
export const FETCH_TWITTER_SAVE_SUCCESS = 'FETCH_TWITTER_SAVE_SUCCESS';
export const FETCH_TWITTER_SAVE_FAILURE = 'FETCH_TWITTER_SAVE_FAILURE';
